name: (OLD) Trigger Windows CPU Build Action

on:
  workflow_dispatch:
    inputs:
      arch:
        description: 'Architecture to build for (x64)'
        required: true
        type: choice
        options:
          - x64

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref && github.ref || github.run_id }}
  cancel-in-progress: true

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  CMAKE_ARGS: "-DLLAMA_BUILD_EXAMPLES=OFF -DLLAMA_BUILD_TESTS=OFF -DLLAMA_BUILD_TOOLS=ON -DLLAMA_BUILD_SERVER=ON -DGGML_RPC=ON"

jobs:
  trigger-build:
    runs-on: windows-2022
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v6

      - name: Trigger Windows CPU Build Workflow
        uses: ./.github/actions/build-windows-cpu
        with:
          arch: ${{ github.event.inputs.arch }}
          CMAKE_ARGS: ${{ env.CMAKE_ARGS }}
